kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go get -v ./...
  - echo "---> Building application source..."
  - go build -v -o main
#  - go install main


- name: echo
  image: golang
  commands:
  - echo "---> finished ..."
